// Run against tests/browser/server.py only: this suite simulates PoE restarts.
require('node:fs').mkdirSync('test-results', {recursive:true});
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1360,height:1000}});const errors=[],remote=[];
 const chooseTheme=async name=>{
   await page.locator('#theme-trigger').click();
   await page.getByRole('button',{name:name+' theme',exact:true}).click();
   assert.equal(await page.locator('#theme-options').isVisible(),false);
 };
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8019'))remote.push(r.url());});
 const visitWithDelayedSession=async url=>{
   let release;
   const gate=new Promise(resolve=>{release=resolve;});
   await page.route('**/api/session',async route=>{await gate;await route.continue();});
   await page.goto(url,{waitUntil:'domcontentloaded'});
   assert.equal((await page.locator('#app').textContent()).trim(),'Loading NetRevive…');
   assert.equal(await page.locator('footer').count(),0);
   const response=page.waitForResponse(r=>r.url().endsWith('/api/session'));
   release();await response;
   await page.unroute('**/api/session');
 };
 await page.emulateMedia({colorScheme:'light'});
 await visitWithDelayedSession('http://127.0.0.1:8019/');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.emulateMedia({colorScheme:'dark'});
 await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
 assert.equal(await page.locator('[data-theme-choice=system]').getAttribute('aria-pressed'),'true');
 await chooseTheme('Light');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.getByLabel('Administrator password',{exact:true}).fill('browser-testing-password');
 await page.getByLabel('Confirm password').fill('browser-testing-password');
 await page.getByRole('button',{name:'Create password & continue'}).click();
 await page.getByLabel('Application display title').waitFor();
 assert.equal(await page.getByLabel('Friendly hostname or URL').count(),0);
 await page.getByRole('button',{name:'Save general settings'}).click();
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByLabel('Controller URL').fill('https://controller.test');
 await page.getByLabel('API key',{exact:true}).fill('browser-test-api-key');
 await page.getByLabel('Verify the controller’s TLS certificate (recommended)').uncheck();
 const draftRequest=page.waitForRequest(r=>r.url().endsWith('/api/admin/unifi/test'));
 await page.getByRole('button',{name:'Test UniFi connection'}).click();
 assert.equal((await draftRequest).postDataJSON().verify_tls,false);
 await page.getByText('Connected and authenticated. These settings have not been saved. Click Save connection to use them.',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('API key',{exact:true}).inputValue(),'browser-test-api-key');
 assert.equal((await (await page.request.get('http://127.0.0.1:8019/api/admin/config')).json()).settings.api_key_configured,false);
 await page.getByRole('button',{name:'Save connection',exact:true}).click();
 await page.getByLabel('Replace API key (leave blank to keep it)').waitFor();
 await page.getByLabel('UniFi site',{exact:true}).selectOption('site-a');
 await page.getByRole('button',{name:'Save site & discover ports'}).click();
 await page.getByText('Discovered PoE ports',{exact:true}).waitFor();
 const switchSections=page.locator('#target-inventory details');
 assert.equal(await switchSections.count(),2);
 assert.equal(await page.locator('#target-inventory details[open]').count(),0);
 const secondSwitch=switchSections.nth(1);
 await secondSwitch.locator('summary').focus();
 await page.keyboard.press('Enter');
 assert.equal(await secondSwitch.getByRole('button').count(),24);
 const tiles=secondSwitch.locator('.port-tile');
 const boxes=await tiles.evaluateAll(els=>els.map(el=>({x:el.offsetLeft,y:el.offsetTop})));
 assert.equal(new Set(boxes.slice(0,12).map(b=>b.y)).size,1);
 assert.equal(new Set(boxes.slice(12).map(b=>b.y)).size,1);
 assert.ok(boxes[12].y>boxes[0].y);
 await secondSwitch.locator('[data-target="42"]').focus();
 await page.keyboard.press('Enter');
 await page.getByLabel('Friendly label',{exact:true}).fill('Firewall');
 await page.getByRole('button',{name:'Save target',exact:true}).click();
 await secondSwitch.getByText('Firewall',{exact:true}).waitFor();
 assert.equal(await page.locator('#target-inventory details[open]').count(),1);
 assert.equal(await page.locator('#target-inventory [data-target="42"]').evaluate(el=>el===document.activeElement),true);
 const editedTargets=(await (await page.request.get('http://127.0.0.1:8019/api/admin/config')).json()).targets;
 assert.equal(editedTargets.find(t=>t.id===42).label,'Firewall');
 assert.equal(editedTargets.find(t=>t.id===1).label,'');
 await page.screenshot({path:'test-results/switch-inventory-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
 assert.ok((await page.evaluate(()=>window.scrollY))>0);
 assert.equal(Math.round((await page.locator('.topbar').boundingBox()).y),0);
 await page.screenshot({path:'test-results/mobile-sticky-navigation.png'});
 await page.screenshot({path:'test-results/switch-inventory-mobile.png',fullPage:true});
 await page.setViewportSize({width:1360,height:1000});
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByLabel('Group name',{exact:true}).fill('Router');
 await page.getByLabel('Button label',{exact:true}).fill('Restart Router');
 await page.getByLabel('Description (optional)').fill('Restarts the equipment that connects you to the internet.');
 await page.locator('input[name=target_ids][value="1"]').check();
 assert.equal(await page.locator('input[name=confirm_targets]').count(),0);
 await page.getByRole('button',{name:'Save restart group'}).click();
 await page.getByText('Restart Router · 1 target · Enabled').waitFor();
 assert.equal(await page.locator('[data-order=groups]').count(),0);
 await page.locator('#add-group').click();
 await page.getByLabel('Group name',{exact:true}).fill('Access points');
 await page.getByLabel('Button label',{exact:true}).fill('Restart APs');
 assert.equal(await page.getByLabel('Display order',{exact:true}).count(),0);
 await page.locator('input[name=target_ids][value="2"]').check();
 await page.getByRole('button',{name:'Save restart group'}).click();
 await page.getByRole('button',{name:'Move Access points up',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-order=groups]')?.getAttribute('aria-label')==='Move Access points up');
 assert.equal(await page.getByRole('button',{name:'Move Access points up',exact:true}).isDisabled(),true);
 assert.equal(await page.getByRole('button',{name:'Move Router down',exact:true}).isDisabled(),true);
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByLabel('Name',{exact:true}).fill('User A');
 await page.getByRole('button',{name:'Add user',exact:true}).click();
 await page.getByText('User A',{exact:true}).waitFor();
 await page.getByLabel('Name',{exact:true}).fill('User B');
 await page.getByRole('button',{name:'Add user',exact:true}).click();
 await page.getByText('User B',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('Display order',{exact:true}).count(),0);
 await page.getByLabel('Name',{exact:true}).fill('Unsaved name');
 await page.getByRole('button',{name:'Move User B up',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('[data-order=users]')?.getAttribute('aria-label')==='Move User B up');
 assert.equal(await page.getByRole('button',{name:'Move User B up',exact:true}).isDisabled(),true);
 assert.equal(await page.getByLabel('Name',{exact:true}).inputValue(),'Unsaved name');
 await page.locator('[data-edit-user]').first().click();
 await page.getByRole('button',{name:'Save user',exact:true}).click();
 await page.getByRole('button',{name:'Add user',exact:true}).waitFor();
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByRole('button',{name:'Save monitoring settings'}).click();
 await page.getByRole('button',{name:'Finish setup'}).click();
 await page.getByRole('heading',{name:'Network overview'}).waitFor();
 assert.equal(await page.locator('#app .eyebrow, #app .group-icon').count(),0);
 assert.equal(await page.getByText('Connected locally',{exact:true}).count(),0);
 assert.equal(await page.locator('.dashboard-title').evaluate(el=>getComputedStyle(el).fontSize),await page.locator('.restart-heading h2').evaluate(el=>getComputedStyle(el).fontSize));
 await page.getByRole('dialog',{name:'Who’s using NetRevive?'}).waitFor();
 assert.equal(await page.locator('#operator option').nth(1).textContent(),'User B');
 assert.equal(await page.evaluate(()=>document.activeElement.id),'operator-title');
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#operator-dialog').evaluate(el=>el.open),true);
 await page.getByLabel('Your name',{exact:true}).selectOption('User A');
 await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
 assert.equal(await page.locator('#operator-dialog').evaluate(el=>el.open),false);
 assert.equal(await page.locator('#current-operator').textContent(),'User A');
 assert.equal(await page.locator('#restart-groups h2, #restart-groups h3').first().textContent(),'Access points');
 const button=page.getByRole('button',{name:'Restart Router',exact:true});
 await button.click();await page.waitForTimeout(200);assert.equal(await page.locator('.activity').count(),0);
 await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(700);await page.keyboard.up('Space');assert.equal(await page.locator('.activity').count(),0);
 const rightEdges=await page.evaluate(()=>[document.querySelector('#theme-trigger').getBoundingClientRect().right,document.querySelector('#restart-groups').getBoundingClientRect().right]);
 assert.ok(Math.abs(rightEdges[0]-rightEdges[1])<2);
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await chooseTheme('Dark');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.screenshot({path:'test-results/dashboard-desktop-dark.png',fullPage:true});
 await page.emulateMedia({colorScheme:'light'});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(2250);await page.keyboard.up('Space');
 await page.locator('.activity').first().waitFor();assert.equal(await button.isDisabled(),true);
 await visitWithDelayedSession('http://127.0.0.1:8019/');await page.getByRole('button',{name:'User A, change user',exact:true}).waitFor().catch(async error=>{console.error(await page.locator('#app').innerText(),errors);throw error;});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 assert.equal(await page.locator('#current-operator').textContent(),'User A');
 assert.equal(await page.locator('#operator-dialog').evaluate(el=>el.open),false);
 await page.getByRole('button',{name:'User A, change user',exact:true}).click();
 await page.getByRole('dialog',{name:'Who’s using NetRevive?'}).waitFor();
 assert.equal(await page.evaluate(()=>document.activeElement.id),'operator-title');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 assert.equal(await page.locator('#current-operator').textContent(),'User A');
 await page.getByRole('button',{name:'User A, change user',exact:true}).click();
 await page.getByLabel('Your name',{exact:true}).selectOption('User B');
 await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
 assert.equal(await page.locator('#current-operator').textContent(),'User B');
 assert.equal(await page.evaluate(()=>localStorage.getItem('netrevive.operator')),'User B');
 await page.evaluate(()=>localStorage.setItem('netrevive.operator','Removed user'));
 await page.reload();await page.getByRole('dialog',{name:'Who’s using NetRevive?'}).waitFor();
 assert.equal(await page.getByLabel('Your name',{exact:true}).inputValue(),'');
 await page.getByLabel('Your name',{exact:true}).selectOption('User A');
 await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'test-results/dashboard-mobile-dark.png',fullPage:true});
 const mobileNavGap=await page.locator('.topbar nav').evaluate(el=>getComputedStyle(el).gap);
 assert.equal(mobileNavGap,'20px');
 await page.setViewportSize({width:1360,height:1000});
 assert.equal(await page.locator('.topbar nav').evaluate(el=>getComputedStyle(el).gap),'28px');
 let adminLeft;
 for(const hash of ['general','unifi','groups']){
   await page.goto('http://127.0.0.1:8019/admin#'+hash);
   await page.locator('#admin-content .panel').first().waitFor();
   const left=(await page.locator('.admin-heading').boundingBox()).x;
   if(adminLeft!==undefined)assert.equal(left,adminLeft,hash+' tab shifts horizontally');
   adminLeft=left;
   if(hash==='groups'){
     const spacing=await page.locator('#admin-content .panel').evaluate(el=>{
       return el.querySelector('.section-head').getBoundingClientRect().top-el.getBoundingClientRect().top-parseFloat(getComputedStyle(el).paddingTop)-parseFloat(getComputedStyle(el).borderTopWidth);
     });
     assert.ok(Math.abs(spacing)<1,'Restart Groups has extra top spacing');
     await page.screenshot({path:'test-results/admin-groups-spacing.png',fullPage:true});
   }
 }
 await page.setViewportSize({width:390,height:844});
 await page.goto('http://127.0.0.1:8019/admin#history');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.getByText('Restart history',{exact:true}).waitFor();await page.locator('summary').first().click();
 await page.getByText('switch-a / 1',{exact:false}).first().waitFor();
 for(const hash of ['general','users','unifi','groups','monitoring','security']){
  await page.goto('http://127.0.0.1:8019/admin#'+hash);await page.locator('#admin-content .panel').first().waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),hash+' mobile overflow');
  assert.equal(await page.locator('#app .eyebrow').count(),0);
  assert.ok(!/\boperators?\b/i.test(await page.locator('#admin-content').innerText()),hash+' uses old user terminology');
  if(hash==='users' || hash==='groups'){
    await page.screenshot({path:'test-results/admin-'+hash+'-ordering-mobile.png',fullPage:true});
  }
  assert.equal(await page.getByRole('link',{name:'Back to dashboard',exact:true}).count(),0);
  const headingRow=await page.evaluate(()=>{
    const heading=document.querySelector('.admin-heading h1').getBoundingClientRect();
    const logout=document.querySelector('#logout').getBoundingClientRect();
    return {difference:Math.abs(heading.y+heading.height/2-logout.y-logout.height/2),right:logout.x>heading.x};
  });
  assert.ok(headingRow.difference<2 && headingRow.right);
  assert.ok(await page.locator('.tabs').evaluate(el=>el.scrollWidth<=el.clientWidth));
  assert.equal(await page.getByRole('heading',{name:'Administration',exact:true}).evaluate(el=>getComputedStyle(el).fontSize),'21px');
 }
 await page.getByLabel('Current password',{exact:true}).fill('browser-testing-password');
 await page.getByLabel('New password',{exact:true}).fill('browser-updated-password');
 await page.getByLabel('Confirm new password',{exact:true}).fill('browser-updated-password');
 await page.getByRole('button',{name:'Change password',exact:true}).click();
 await page.getByText('Administrator password changed.',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('New password',{exact:true}).inputValue(),'');
 await page.locator('#theme-trigger').focus();
 await page.keyboard.press('ArrowDown');
 assert.equal(await page.evaluate(()=>document.activeElement.getAttribute('aria-pressed')),'true');
 assert.equal(await page.locator('#theme-options').isVisible(),true);
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#theme-options').isVisible(),false);
 assert.equal(await page.evaluate(()=>document.activeElement.id),'theme-trigger');
 await page.locator('#theme-trigger').click();
 await page.getByRole('heading',{name:'Administration',exact:true}).click();
 assert.equal(await page.locator('#theme-options').isVisible(),false);
 assert.equal(await page.getByRole('navigation',{name:'Main',exact:true}).getByRole('link',{name:'Dashboard',exact:true}).count(),0);
 await chooseTheme('Auto');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 assert.equal(await page.evaluate(()=>localStorage.getItem('netrevive.theme')),null);
 await page.reload();
 await page.locator('#theme-trigger').waitFor();
 assert.equal(await page.locator('[data-theme-choice=system]').getAttribute('aria-pressed'),'true');
 await page.emulateMedia({colorScheme:'dark'});
 await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
 await page.getByRole('link',{name:'NetRevive dashboard',exact:true}).click();
 await page.getByRole('heading',{name:'Network overview',exact:true}).waitFor();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 assert.equal(await page.getByRole('button',{name:'User A, change user',exact:true}).textContent(),'User A');
 await page.screenshot({path:'test-results/dashboard-system-theme-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
 console.log('PASS: complete first-run setup, authenticated administration, real API persistence, click/short-hold cancellation, keyboard hold restart, lockout, remembered operator, detailed history, mobile layouts, no remote assets or JS errors.');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
