// Run against tests/browser/server.py only: this suite simulates PoE restarts.
require('node:fs').mkdirSync('test-results', {recursive:true});
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
try{
 const page=await browser.newPage({viewport:{width:1360,height:1000}});const errors=[],remote=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1:8019'))remote.push(r.url());});
 await page.emulateMedia({colorScheme:'light'});
 await page.goto('http://127.0.0.1:8019/');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.emulateMedia({colorScheme:'dark'});
 await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
 assert.equal(await page.getByRole('button',{name:'Auto theme',exact:true}).getAttribute('aria-pressed'),'true');
 await page.getByRole('button',{name:'Light theme',exact:true}).click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 await page.getByLabel('Administrator password',{exact:true}).fill('browser-testing-password');
 await page.getByLabel('Confirm password').fill('browser-testing-password');
 await page.getByRole('button',{name:'Create password & continue'}).click();
 await page.getByLabel('Application display title').waitFor();
 await page.getByRole('button',{name:'Save general settings'}).click();
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByLabel('Controller URL').fill('https://controller.test');
 await page.getByLabel('API key',{exact:true}).fill('browser-test-api-key');
 await page.getByLabel('Verify the controller’s TLS certificate (recommended)').uncheck();
 const draftRequest=page.waitForRequest(r=>r.url().endsWith('/api/admin/unifi/test'));
 await page.getByRole('button',{name:'Test UniFi connection'}).click();
 assert.equal((await draftRequest).postDataJSON().verify_tls,false);
 await page.getByText('Connected and authenticated. These settings have not been saved. Click Save connection to use them.',{exact:true}).waitFor();
 assert.equal(await page.getByLabel('API key',{exact:true}).inputValue(),'browser-test-api-key');
 assert.equal((await (await page.request.get('http://127.0.0.1:8019/api/admin/config')).json()).settings.api_key_configured,false);
 await page.getByRole('button',{name:'Save connection',exact:true}).click();
 await page.getByLabel('Replace API key (leave blank to keep it)').waitFor();
 await page.getByLabel('UniFi site',{exact:true}).selectOption('site-a');
 await page.getByRole('button',{name:'Save site & discover ports'}).click();
 await page.getByText('Discovered PoE ports',{exact:true}).waitFor();
 const switchSections=page.locator('#target-inventory details');
 assert.equal(await switchSections.count(),2);
 assert.equal(await page.locator('#target-inventory details[open]').count(),0);
 const secondSwitch=switchSections.nth(1);
 await secondSwitch.locator('summary').focus();
 await page.keyboard.press('Enter');
 assert.equal(await secondSwitch.getByRole('button').count(),24);
 const tiles=secondSwitch.locator('.port-tile');
 const boxes=await tiles.evaluateAll(els=>els.map(el=>({x:el.offsetLeft,y:el.offsetTop})));
 assert.equal(new Set(boxes.slice(0,12).map(b=>b.y)).size,1);
 assert.equal(new Set(boxes.slice(12).map(b=>b.y)).size,1);
 assert.ok(boxes[12].y>boxes[0].y);
 await secondSwitch.locator('[data-target="42"]').focus();
 await page.keyboard.press('Enter');
 await page.getByLabel('Friendly label',{exact:true}).fill('Firewall');
 await page.getByRole('button',{name:'Save target',exact:true}).click();
 await secondSwitch.getByText('Firewall',{exact:true}).waitFor();
 assert.equal(await page.locator('#target-inventory details[open]').count(),1);
 assert.equal(await page.locator('#target-inventory [data-target="42"]').evaluate(el=>el===document.activeElement),true);
 const editedTargets=(await (await page.request.get('http://127.0.0.1:8019/api/admin/config')).json()).targets;
 assert.equal(editedTargets.find(t=>t.id===42).label,'Firewall');
 assert.equal(editedTargets.find(t=>t.id===1).label,'');
 await page.screenshot({path:'test-results/switch-inventory-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.evaluate(()=>window.scrollTo(0,document.body.scrollHeight));
 assert.ok((await page.evaluate(()=>window.scrollY))>0);
 assert.equal(Math.round((await page.locator('.topbar').boundingBox()).y),0);
 await page.screenshot({path:'test-results/mobile-sticky-navigation.png'});
 await page.screenshot({path:'test-results/switch-inventory-mobile.png',fullPage:true});
 await page.setViewportSize({width:1360,height:1000});
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByLabel('Group name',{exact:true}).fill('Router');
 await page.getByLabel('Button label',{exact:true}).fill('Restart Router');
 await page.getByLabel('Description (optional)').fill('Restarts the equipment that connects you to the internet.');
 await page.locator('input[name=target_ids][value="1"]').check();
 assert.equal(await page.locator('input[name=confirm_targets]').count(),0);
 await page.getByRole('button',{name:'Save restart group'}).click();
 await page.getByText('Restart Router · 1 target · Enabled').waitFor();
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByLabel('Name',{exact:true}).fill('Operator A');
 await page.getByRole('button',{name:'Add operator',exact:true}).click();
 await page.getByText('Operator A',{exact:true}).waitFor();
 await page.getByLabel('Name',{exact:true}).fill('Operator B');
 await page.getByRole('button',{name:'Add operator',exact:true}).click();
 await page.getByText('Operator B',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Continue →'}).click();
 await page.getByRole('button',{name:'Save monitoring settings'}).click();
 await page.getByRole('button',{name:'Finish setup'}).click();
 await page.getByRole('heading',{name:'Network overview'}).waitFor();
 assert.equal(await page.locator('#app .eyebrow, #app .group-icon').count(),0);
 assert.equal(await page.getByText('Connected locally',{exact:true}).count(),0);
 assert.equal(await page.locator('.dashboard-title').evaluate(el=>getComputedStyle(el).fontSize),await page.locator('.restart-heading h2').evaluate(el=>getComputedStyle(el).fontSize));
 await page.getByRole('dialog',{name:'Who’s using NetRevive?'}).waitFor();
 assert.equal(await page.evaluate(()=>document.activeElement.id),'operator-title');
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('#operator-dialog').evaluate(el=>el.open),true);
 await page.getByLabel('Your name',{exact:true}).selectOption('Operator A');
 await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
 assert.equal(await page.locator('#operator-dialog').evaluate(el=>el.open),false);
 assert.equal(await page.locator('#current-operator').textContent(),'Operator A');
 const button=page.getByRole('button',{name:'Restart Router',exact:true});
 await button.click();await page.waitForTimeout(200);assert.equal(await page.locator('.activity').count(),0);
 await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(700);await page.keyboard.up('Space');assert.equal(await page.locator('.activity').count(),0);
 const rightEdges=await page.evaluate(()=>[document.querySelector('.theme-options').getBoundingClientRect().right,document.querySelector('#restart-groups').getBoundingClientRect().right]);
 assert.ok(Math.abs(rightEdges[0]-rightEdges[1])<2);
 await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Dark theme',exact:true}).click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.screenshot({path:'test-results/dashboard-desktop-dark.png',fullPage:true});
 await page.emulateMedia({colorScheme:'light'});
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await button.focus();await page.keyboard.down('Space');await page.waitForTimeout(2250);await page.keyboard.up('Space');
 await page.locator('.activity').first().waitFor();assert.equal(await button.isDisabled(),true);
 await page.reload();await page.getByRole('button',{name:'Operator A, change user',exact:true}).waitFor();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 assert.equal(await page.locator('#current-operator').textContent(),'Operator A');
 assert.equal(await page.locator('#operator-dialog').evaluate(el=>el.open),false);
 await page.getByRole('button',{name:'Operator A, change user',exact:true}).click();
 await page.getByRole('dialog',{name:'Who’s using NetRevive?'}).waitFor();
 assert.equal(await page.evaluate(()=>document.activeElement.id),'operator-title');
 await page.getByRole('button',{name:'Cancel',exact:true}).click();
 assert.equal(await page.locator('#current-operator').textContent(),'Operator A');
 await page.getByRole('button',{name:'Operator A, change user',exact:true}).click();
 await page.getByLabel('Your name',{exact:true}).selectOption('Operator B');
 await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
 assert.equal(await page.locator('#current-operator').textContent(),'Operator B');
 assert.equal(await page.evaluate(()=>localStorage.getItem('netrevive.operator')),'Operator B');
 await page.evaluate(()=>localStorage.setItem('netrevive.operator','Removed user'));
 await page.reload();await page.getByRole('dialog',{name:'Who’s using NetRevive?'}).waitFor();
 assert.equal(await page.getByLabel('Your name',{exact:true}).inputValue(),'');
 await page.getByLabel('Your name',{exact:true}).selectOption('Operator A');
 await page.getByRole('button',{name:'Open dashboard',exact:true}).click();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 await page.screenshot({path:'test-results/dashboard-mobile-dark.png',fullPage:true});
 await page.goto('http://127.0.0.1:8019/admin#history');
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 await page.getByText('Restart history',{exact:true}).waitFor();await page.locator('summary').first().click();
 await page.getByText('switch-a / 1',{exact:false}).first().waitFor();
 for(const hash of ['general','users','unifi','groups','monitoring']){
  await page.goto('http://127.0.0.1:8019/admin#'+hash);await page.locator('#admin-content .panel').first().waitFor();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),hash+' mobile overflow');
  assert.equal(await page.locator('#app .eyebrow').count(),0);
  assert.equal(await page.getByRole('heading',{name:'Administration',exact:true}).evaluate(el=>getComputedStyle(el).fontSize),'21px');
 }
 assert.equal(await page.getByRole('navigation',{name:'Main',exact:true}).getByRole('link',{name:'Dashboard',exact:true}).count(),0);
 await page.getByRole('button',{name:'Auto theme',exact:true}).click();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'light');
 assert.equal(await page.evaluate(()=>localStorage.getItem('netrevive.theme')),null);
 await page.reload();
 await page.getByRole('button',{name:'Auto theme',exact:true}).waitFor();
 assert.equal(await page.getByRole('button',{name:'Auto theme',exact:true}).getAttribute('aria-pressed'),'true');
 await page.emulateMedia({colorScheme:'dark'});
 await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');
 await page.getByRole('link',{name:'NetRevive dashboard',exact:true}).click();
 await page.getByRole('heading',{name:'Network overview',exact:true}).waitFor();
 assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');
 assert.equal(await page.getByRole('button',{name:'Operator A, change user',exact:true}).textContent(),'Operator A');
 await page.screenshot({path:'test-results/dashboard-system-theme-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);assert.deepEqual(remote,[]);
 console.log('PASS: complete first-run setup, authenticated administration, real API persistence, click/short-hold cancellation, keyboard hold restart, lockout, remembered operator, detailed history, mobile layouts, no remote assets or JS errors.');
}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
